### ISSUE TITLE
Unable to interact with objects on the Scrapbook with the selection tool

### ISSUE THREAD

**Issue by syesil00** [info442-spr22/g-team#129]
MAJOR - I am able to select objects on the Sketchbook with the selection tool; however, I am unable to interact with them at all (e.g. cannot move objects, cannot change their color, etc). 

Steps:
Place object on sketchbook canvas -> choose selection tool -> select object -> object is outlined but cannot do anything else.

Expected result: Select and move objects.
Actual result: Outline of object.

Google Chrome Version 101.0.4951.67 (Official Build) (64-bit) on Windows 11

**Comment by nihagaddam** [comment]
Duplicate Issue, Original Issue: #127
