### ISSUE TITLE
Canvas doesn't fully clear

### ISSUE THREAD

**Issue by spudists** [info442-spr22/g-team#130]
Major
When clicking on "Restart" and selecting "Yes, clear my canvas", the text box that I created remains on the screen.   This is problematic because there isn't a clear way to remove the item aside from deleting all the text that it contains.  This is challenging for the user to understand.
Chrome, HP Pavilion
I expected to be able to select and delete items individually, as well as see a fully clear canvas when selecting Restart

**Comment by cherimarie** [comment]
I can repro in Chrome on MacOS. This is a major bug.

**Comment by cavazd** [comment]
Will need to remove elements from the list after clearing so they are not automatically redrawn
