### ISSUE TITLE
Bug: Clear canvas "Restart" button. (Major)

### ISSUE THREAD

**Issue by GuillyGuillaume** [info442-spr22/g-team#131]
Clicking "Yes, clear my canvas" after receiving prompt from pressing "Restart":
Expect: Clear canvas.
Actual: Button does nothing.

Clicking "No, don't clear my canvas":
Expect: Canvas elements to not change.
Actual: Clears all content on the canvas until I place another element on the canvas, in which case all previously placed canvas elements reappear. 

Environment: Google Chrome Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by cherimarie** [comment]
I can repro in Chrome on MacOS. This is a major bug.
