### ISSUE TITLE
Bug: Cannot clear canvas after clicking clear button

### ISSUE THREAD

**Issue by stroz08** [info442-spr22/g-team#132]
Severity: major
Summary: When I click on the restart button and click 'yes, clear my canvas', the canvas appears to be reset but upon placing a new shape it bring back my old canvas.
Environment: Chrome Version 101.0.4951.67, Windows 10
Steps to reproduce: Draw on canvas, click restart, click 'yes, clear my canvas', place a new shape.
Expected Result: A clear, editable canvas.
Actual Result: Old Canvas

**Comment by cherimarie** [comment]
I can repro in Chrome on MacOS. This is a major bug.
