### ISSUE TITLE
(Enhancement) Scrapbook save button

### ISSUE THREAD

**Issue by Jaehoon01** [info442-spr22/g-team#134]
On the scrapbook, after I finished my design and clicked save, I wasn't notified or anything that it was saved so I didn't know until I went to the gallery. Chrome on MacOS.

**Comment by nihagaddam** [comment]
This is a design issue: Save button is functional, but does not implement user feedback to notify them that their work has been saved. A pop-up window should be made with a message to let user know their work has been saved.
