### ISSUE TITLE
Not intuitive on mobile devices/media queries are not there for mobile app. (Minor) (Bug)

### ISSUE THREAD

**Issue by avaghela-1925502** [info442-spr22/g-team#140]
Web app is not fit for mobile app as much of the alignment is off and does not allow it to become intuitive for the user. 

Encountered on chrome.

Steps to reproduce: Add media queries to format the css styling on pages to fit the colored boxes
Expected result: Formatted text
Actual result: Unformatted text/buttons

**Comment by KexinPei** [comment]
Duplicate, similar solution as issue#128, different environment&specification
https://github.com/info442-spr22/g-team/issues/128#issue-1240180430
