### ISSUE TITLE
Bug: Refreshing on scrapbook and gallery pages produces "Page Not Found" error. (Minor)

### ISSUE THREAD

**Issue by GuillyGuillaume** [info442-spr22/g-team#144]
Refreshing the browser on a routed page (ie. ....netlify.app/scrapbook or ....netlify.app/gallery):
Expect: Page to refresh with same/similar content.
Actual: Prompted with "Page Not Found" error (shown below).

Environment: Google Chrome Version 101.0.4951.67 (Official Build) (64-bit)

![Screenshot 2022-05-18 091330](https://user-images.githubusercontent.com/62913726/169091565-08880d51-1418-47a5-9ae5-70cd65838ed7.png)

**Comment by fretws** [comment]
This is a known issue with netlify, we should be able to fix it with a change to netlify settings
