### ISSUE TITLE
[Minor Issue] Selection of shapes is not reliable

### ISSUE THREAD

**Issue by MARY4177** [info442-spr22/g-team#146]
When trying to draw boxes using two different shapes available to use, the shapes are not different when drawing on the canvas when it is expected to draw a square and a rectangle. Same issue for circles.
● environment it was encountered in MacOS Chrome
● steps to reproduce: Click on one of the tool shapes, draw on canvas -> click on other shape and draw it on canvas -> compare the results
● expected result: The drawing should produce different shapes when clicking on different tool shapes to use.
● actual result: Same shapes for rectangles and same shapes for circles (no differences)
● optional attachments (screenshots, error logs, etc)
<img width="801" alt="스크린샷 2022-05-18 오전 9 16 54" src="https://user-images.githubusercontent.com/55933930/169091996-077ef457-a41c-4f20-a7a1-bad6c845434e.png">

**Comment by fretws** [comment]
When the user clicks, sometimes it is registered as a click and drag even though that isn't what the user intended. We can change the onClick to be an onMouseUp listener

**Comment by sharlenef** [comment]
In addition, we will provide users with more feedback about when a shape is selected so that they know which shape they're currently on
