### ISSUE TITLE
Drawing Briefly Disappears *BUG*

### ISSUE THREAD

**Issue by epdooley** [info442-spr22/g-team#149]
Minor 
When I click 'Restart', my drawing disappears as the pop-up shows up. If I then click the 'X' button to escape the pop-up, my drawing remains gone until I click again on the canvas.
I encountered this using Google Chrome on macOS Monterey.
I would expect my drawing to stay on the canvas when the pop-up is open and when it is closed. If it is difficult to have it appear when the pop-up is showing, I would at least expect it to come back after I close the pop-up. If I didn't click on the canvas again, I may have just thought the drawing was gone.

**Comment by cavazd** [comment]
Duplicate

Original: #130
