### ISSUE TITLE
[Minor Issue] Can not put multiple text boxes

### ISSUE THREAD

**Issue by MARY4177** [info442-spr22/g-team#150]
When trying to put multiple texts on canvas, it does not work.
● environment it was encountered in MacOS chrome
● steps to reproduce: Click on the text feature, click on the canvas to write down the text -> do the same process
● expected result: Multiple different text boxes
● actual result: Only showing one text box
● optional attachments (screenshots, error logs, etc)
<img width="801" alt="스크린샷 2022-05-18 오전 9 16 54" src="https://user-images.githubusercontent.com/55933930/169093046-120cdfc7-11b1-4abb-9477-71d2bf82260c.png">

**Comment by cavazd** [comment]
Duplicate

Original: #143
