### ISSUE TITLE
Text Doesn't Clear From Canvas *BUG*

### ISSUE THREAD

**Issue by epdooley** [info442-spr22/g-team#151]
Minor
When I clear the canvas, all of the shapes get erased but the text box doesn't. It seems that there is currently not a way to get rid of a text box once you have placed it. 
I encountered this using Google Chrome on macOS Monterey.
I would expect the text box to also be cleared when I click 'Yes, clear all.'

**Comment by fretws** [comment]
Could not reproduce on Windows 10, Microsoft Edge
