### ISSUE TITLE
[Enhancement] Letting user know if their drawing has been saved

### ISSUE THREAD

**Issue by kasayachith** [info442-spr22/g-team#156]
After drawing something, I clicked on the "save" button and nothing happened on that page so I was confused if it was doing anything or not (but it does work because I saw my drawing in the gallery). I think it would be helpful to show the user that their drawing has been successfully saved to show them that the system actually did something through a pop-up message of some sort.

**Comment by sharlenef** [comment]
Duplicate of #134 (#139, #155, #156, #171)
