### ISSUE TITLE
Minor Bug: Unable to move around shapes with cursor

### ISSUE THREAD

**Issue by jeannechoi00** [info442-spr22/g-team#158]
**Summary of the problem:**
- The cursor in the scrapbook feature does not let me move around or edit any of the current shapes/text boxes that are inside the drawing.
**Encountered in:** Chrome v90.0.4430.85 

**Expected result:** Allowing for shapes to be moved around the box
**Actual result:** Static shapes that are highlighted when selected with cursor but not able to move around

**Comment by fretws** [comment]
This is a known issue, We were in the middle of stickers when the development sprint ended.

**Comment by nihagaddam** [comment]
Duplicate Issue, Original Issue: #127
