### ISSUE TITLE
Major bug: the share button on the gallery page does not function

### ISSUE THREAD

**Issue by xxiaouw** [info442-spr22/g-team#159]
When clicking on the share button for an saved art in the gallery page, a pop up window with placeholder text (I think) shows up. When clicking on Twitter, a pop up for the webpage shows up and says something went wrong. I was expecting to maybe be redirected to Twitter.

**Comment by fretws** [comment]
This is a known issue. Twitter suspended our API access an hour after the second development sprint ended.

**Comment by nihagaddam** [comment]
Duplicate, Original: #133
