### ISSUE TITLE
[Minor Bug] Select button doesn't do anything

### ISSUE THREAD

**Issue by MARY4177** [info442-spr22/g-team#161]
Although the select button allows users to actually select a line or a shape they drew, it does not do anything further than that.
● environment it was encountered in: MacOS Chrome
● steps to reproduce: Click on select tool -> click on shape
● expected result: Should be able to do something more than just selecting a shape; For example, they can move around the shapes.
● actual result: Does not do anything more than just clicking on the shape
● optional attachments (screenshots, error logs, etc):
<img width="803" alt="스크린샷 2022-05-18 오전 9 40 45" src="https://user-images.githubusercontent.com/55933930/169096524-5fad9f3a-f995-4b35-b59c-ea0225cfb7c9.png">

**Comment by nihagaddam** [comment]
Duplicate Issue, Original Issue: #127
