### ISSUE TITLE
Minor Bugs: Media Queries/resize of window not working

### ISSUE THREAD

**Issue by jeannechoi00** [info442-spr22/g-team#163]
**Summary of the problem**
- When resizing the screen the scrapbook itself does not resize with it so the features/scrapbook items are not able to be used unless the screen is full size
**Encountered in** Chrome v90.0.4430.85 on macOS Catalina
Expected result: For all features in the scrapbook to resize/adjust based on screen
actual result: they do not change

example with smaller window size
<img width="556" alt="Screen Shot 2022-05-18 at 9 42 33 AM" src="https://user-images.githubusercontent.com/76883010/169096844-e7c6d316-5614-4500-84d6-36542c90278b.png">

**Comment by fretws** [comment]
Same solution as #148
