### ISSUE TITLE
(Minor) Canvas not restored automatically after clicking on "No, don't clear my canvas" button

### ISSUE THREAD

**Issue by soopark82** [info442-spr22/g-team#164]
After clicking on "Restart" followed by clicking on "No, don't clear my canvas", the drawing doesn't appear back until I clicked on the canvas. 

Severity: minor
Environment: Chrome v101.0.4951.67 on Windows
expected result: the drawing should appear automatically after clicking on "No, don't clear my canvas" even without clicking on the canvas, or have a feedback message that guides the user to click on the map to see the drawing again.
actual result: the drawing didn't appear back on until I clicked on the canvas

**Comment by KexinPei** [comment]
Duplicate, a similar issue as Drawing Briefly Disappears *BUG* #149, but in different environments
https://github.com/info442-spr22/g-team/issues/149#issue-1240202148
