### ISSUE TITLE
(BUG, Minor): Share feature has filler text description

### ISSUE THREAD

**Issue by RachelChung2020** [info442-spr22/g-team#167]
The Share feature has lorem ipsum text and says "Example Title"

Environment it was encountered in: Chrome v101.0.4951.67 in Windows

**Steps to reproduce:**
1. Go to Gallery
2. Click on image
3. Click share button

Expected result: customized instructions

Actual result:: lorem ipusm text

**Comment by sharlenef** [comment]
Dupllicate of #135
