### ISSUE TITLE
(minor bug) can't access the save and cancel button since the webpage doesn't resize while zooming in and out

### ISSUE THREAD

**Issue by Yueemxn** [info442-spr22/g-team#173]
- general summary of the problem
  - I can only see half of the buttons on my end of the computer and it can be difficult for me to find them immediately.
- environment it was encountered in (Chrome v90on
macOS Catalina)
- steps to reproduce
  -Get to the mainpage, click on get started, get redirected to the canvas, unable to find "save" or "cancel" button at first
- expected result
  -see the buttons right away while zooming in and out of the screen
- actual result
  -the buttons were hidden after zooming in and out

**Comment by fretws** [comment]
Same solution as #148
