### ISSUE TITLE
Core Feature: Scrapbook (art creation/journal page)

### ISSUE THREAD

**Issue by nihagaddam** [info442-spr22/g-team#3]
List out requirements for Scrapbook Page.

**Comment by KexinPei** [comment]
- Users can place pre-selected shapes on canvas
Scale shapes
Change color

-Users can place self-created shapes on canvas
Scale shapes
Change color

-Change canvas background-color

-Users can write text on canvas
Change font size / type / style
Change font color

-Users can save content to gallery
Save to calendar (stretch)

-Users need an account to save to the gallery.
log in & sign up

-Users can utilize gallery content and place it on canvass
Scale content

-Clear button to remove all content from the page
