### ISSUE TITLE
Implement sticker selection on canvas

### ISSUE THREAD

**Issue by fretws** [info442-spr22/g-team#66]
Find the button in the action bar for the select + move tool from #75. The user can only select the stickers on the canvas when this button is toggled on.

When a sticker on the canvas is selected, update the page state to track which sticker is selected.
While an object is selected,
 - [x] it gains a square outline that is dashed and black
 - [x] if a portion of the canvas with no object is clicked, the object is de-selected

**Comment by cavazd** [comment]
Currently only works for rectangle and line

**Comment by cavazd** [comment]
Everything but heart selection, can still select multiple elements, can select an element more than once

**Comment by cavazd** [comment]
- [ ] Add heart selection
- [ ] Can only select one element
- [ ] Clicking on an element multiple times does not redraw selection box
- [ ] Add hotkey for select button
